### ISSUE TITLE
Automatic builds

### ISSUE THREAD

**Issue by Lipovlan** [Lipovlan/cng-openssl-provider#9]
A nice feature to have would be automatic builds on GitHub that would create x86 and x64 packages of the provider in both normal and debug version.

**Comment by levitte** [comment]
Incidently, I have played around with github actions in my fork. See my [workflow](https://github.com/levitte/cng-openssl-provider/tree/workflow) branch.

**Comment by Lipovlan** [comment]
Nice! I've pulled the branch into my repo and will try to play with it :)

**Comment by Lipovlan** [comment]
I have made the automatic builds work! The code has been merged as of a5f3969. I would also like to work on caching OpenSSL builds as it takes a lot of time (and computing time, so it gets limited by GitHub and thus even slower).

**Comment by levitte** [comment]
Cool!  Glad I could help!
